"use client";

import { useState } from "react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { PenSquare, Clock, Newspaper, Bot, ExternalLink, CalendarClock } from "lucide-react";
import Link from "next/link";
import { DraftDeleteButton } from "@/components/drafts/draft-delete-button";
import { BatchGenerateDialog } from "@/components/drafts/batch-generate-dialog";
import { ScheduleDraftDialog } from "@/components/drafts/schedule-draft-dialog";

export interface DraftItem {
  id: string;
  text: string;
  status: string;
  source: string;
  hashtags: string[] | null;
  media_urls: string[] | null;
  metadata: Record<string, unknown> | null;
  created_at: string;
  updated_at: string;
  account_id?: string;
  social_accounts?: { username: string; platform: string } | { username: string; platform: string }[];
  scheduled_posts?: { id: string; scheduled_at: string; status: string }[];
}

interface DraftsViewProps {
  drafts: DraftItem[];
  accountId?: string | null;
}

const statusLabels: Record<string, { label: string; variant: "default" | "secondary" | "outline" }> = {
  draft: { label: "下書き", variant: "secondary" },
  scheduled: { label: "予約済み", variant: "default" },
};

const sourceLabels: Record<string, string> = {
  manual: "手動作成",
  openclaw: "OpenClaw",
  ai: "AI生成",
};

export function DraftsView({ drafts, accountId }: DraftsViewProps) {
  const [scheduleTarget, setScheduleTarget] = useState<{
    draftId: string;
    accountId: string;
    text: string;
  } | null>(null);

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold">下書き</h1>
        <div className="flex items-center gap-2">
          {accountId && <BatchGenerateDialog accountId={accountId} />}
          <Button asChild>
            <Link href="/compose">
              <PenSquare className="mr-2 h-4 w-4" />
              新規作成
            </Link>
          </Button>
        </div>
      </div>

      {drafts && drafts.length > 0 ? (
        <div className="space-y-3">
          {drafts.map((draft) => {
            const account = Array.isArray(draft.social_accounts)
              ? draft.social_accounts[0]
              : draft.social_accounts;
            const statusInfo = statusLabels[draft.status] ?? {
              label: draft.status,
              variant: "outline" as const,
            };

            const meta = draft.metadata;
            const sourceUrl = meta?.source_url as string | undefined;
            const rssSource = meta?.rss_source as string | undefined;
            const isAutoGenerated = meta?.auto_generated === true;

            const scheduledPost = Array.isArray(draft.scheduled_posts)
              ? draft.scheduled_posts.find(
                  (sp) => sp.status === "pending" || sp.status === "processing"
                )
              : undefined;

            const resolvedAccountId = draft.account_id || accountId || "";

            return (
              <Card key={draft.id}>
                <CardContent className="py-4">
                  <div className="flex items-start justify-between gap-4">
                    <div className="flex-1 min-w-0 space-y-2">
                      <p className="text-sm line-clamp-3">{draft.text}</p>

                      <div className="flex items-center gap-2 flex-wrap">
                        <Badge variant={statusInfo.variant}>
                          {statusInfo.label}
                        </Badge>
                        {scheduledPost && (
                          <Badge variant="outline" className="text-xs gap-1 text-blue-600 border-blue-300">
                            <CalendarClock className="h-3 w-3" />
                            {new Date(scheduledPost.scheduled_at).toLocaleDateString("ja-JP", {
                              month: "short",
                              day: "numeric",
                              hour: "2-digit",
                              minute: "2-digit",
                            })}{" "}
                            予約中
                          </Badge>
                        )}
                        {account && (
                          <Badge variant="outline" className="text-xs">
                            @{account.username}
                          </Badge>
                        )}
                        <span className="text-xs text-muted-foreground">
                          {sourceLabels[draft.source] ?? draft.source}
                        </span>
                        {sourceUrl && (
                          <a
                            href={sourceUrl}
                            target="_blank"
                            rel="noopener noreferrer"
                            className="inline-flex items-center gap-1"
                          >
                            <Badge variant="outline" className="text-[10px] px-1.5 py-0 gap-1 text-orange-600 border-orange-300">
                              <Newspaper className="h-2.5 w-2.5" />
                              {rssSource ?? "RSS"}
                              <ExternalLink className="h-2 w-2" />
                            </Badge>
                          </a>
                        )}
                        {isAutoGenerated && (
                          <Badge variant="secondary" className="text-[10px] px-1.5 py-0 gap-1">
                            <Bot className="h-2.5 w-2.5" />
                            自動生成
                          </Badge>
                        )}
                        <span className="text-xs text-muted-foreground flex items-center gap-1">
                          <Clock className="h-3 w-3" />
                          {new Date(draft.updated_at).toLocaleDateString("ja-JP", {
                            month: "short",
                            day: "numeric",
                            hour: "2-digit",
                            minute: "2-digit",
                          })}
                        </span>
                      </div>

                      {draft.hashtags && draft.hashtags.length > 0 && (
                        <div className="flex gap-1 flex-wrap">
                          {draft.hashtags.map((tag: string, i: number) => (
                            <Badge key={i} variant="secondary" className="text-xs">
                              {tag}
                            </Badge>
                          ))}
                        </div>
                      )}

                      {draft.media_urls && draft.media_urls.length > 0 && (
                        <div className="flex gap-2 overflow-x-auto">
                          {draft.media_urls.map((url: string, i: number) => (
                            <img
                              key={i}
                              src={url}
                              alt={`メディア ${i + 1}`}
                              className="h-16 w-16 rounded-md object-cover border shrink-0"
                            />
                          ))}
                        </div>
                      )}
                    </div>

                    <div className="flex gap-0.5 md:gap-1 shrink-0">
                      {draft.status === "draft" && !scheduledPost && resolvedAccountId && (
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-10 w-10"
                          title="予約する"
                          onClick={() =>
                            setScheduleTarget({
                              draftId: draft.id,
                              accountId: resolvedAccountId,
                              text: draft.text,
                            })
                          }
                        >
                          <CalendarClock className="h-5 w-5 text-blue-500" />
                        </Button>
                      )}
                      <Button variant="ghost" size="icon" className="h-10 w-10" asChild>
                        <Link href={`/compose?draft=${draft.id}`}>
                          <PenSquare className="h-5 w-5" />
                        </Link>
                      </Button>
                      <DraftDeleteButton draftId={draft.id} />
                    </div>
                  </div>
                </CardContent>
              </Card>
            );
          })}
        </div>
      ) : (
        <Card>
          <CardContent className="py-12 text-center">
            <PenSquare className="mx-auto h-12 w-12 text-muted-foreground" />
            <h3 className="mt-4 text-lg font-medium">下書きがありません</h3>
            <p className="mt-2 text-sm text-muted-foreground">
              新しい投稿を作成して下書きに保存しましょう。
            </p>
            <Button className="mt-4" asChild>
              <Link href="/compose">新規作成</Link>
            </Button>
          </CardContent>
        </Card>
      )}

      {scheduleTarget && (
        <ScheduleDraftDialog
          open={!!scheduleTarget}
          onOpenChange={(open) => {
            if (!open) setScheduleTarget(null);
          }}
          draftId={scheduleTarget.draftId}
          accountId={scheduleTarget.accountId}
          draftText={scheduleTarget.text}
        />
      )}
    </div>
  );
}
